export const ADD_GROUP = "ADD_GROUP";

export const FETCH_GROUPS = "FETCH_GROUPS";
export const FETCH_GROUPS_ERROR = "FETCH_GROUPS_ERROR";


export const LOAD_GROUP = "LOAD_GROUP";
export const LOAD_GROUP_ERRORS = "LOAD_GROUP_ERRORS";

export const LOAD_RANDOM_GROUPS = "LOAD_RANDOM_GROUPS";
export const LOAD_RANDOM_GROUPS_ERRORS = "LOAD_RANDOM_GROUPS_ERRORS";


export const JOIN_INTO_GROUP = "JOIN_INTO_GROUP";