export const LOGING_IN = 'LOGING_IN';
export const LOGING_ERROR = 'LOGING_ERROR';
export const LOGING_OUT = 'LOGING_OUT';

export const SETTING_LOCAL_STORAGE_SUPPORT_ERROR = 'SETTING_LOCAL_STORAGE_SUPPORT_ERROR';