export const CHANGING_POST_TITLE = "CHANGING_POST_TITLE";
export const CHANGING_POST_CONTENT = "CHANGING_POST_CONTENT";
export const REDIRECTING_TO_TRUE = "REDIRECTING_TO_TRUE";
export const LOADING_POSTS = 'LOADING_POSTS';
export const FETCHING_POSTS_FAILED = 'FETCHING_POSTS_FAILED';
export const CHANGING_SPINNER_STATE = 'CHANGING_SPINNER_STATE';