export const FETCH_USER_GROUPS = 'FETCH_USER_GROUPS';
export const FETCH_USER_GROUPS_ERROR = 'FETCH_USER_GROUPS_ERROR';


export const ADD_POST = 'ADD_POST';

export const FETCH_USER_POSTS = 'FETCH_USER_POSTS';
export const FETCH_USER_POSTS_ERRORS = "FETCH_USER_POSTS_ERRORS";


export const DELETE_POST = "DELETE_POST";

export const EDIT_POST = "EDIT_POST";

export const FETCH_EDIT_POST = "FETCH_EDIT_POST";