export const FETCHING_EVENTS = "FETCHING_EVENTS";
export const FETCHING_EVENTS_ERRORS = "FETCHING_EVENTS_ERRORS";

export const ADD_EVENT = "ADD_EVENT";


export const FETCH_ONE_EVENT = "FETCH_ONE_EVENT";
export const FETCH_ONE_EVENT_ERROR = "FETCH_ONE_EVENT_ERROR";


export const FETCH_EVENTS = "FETCH_EVENTS";
export const FETCH_EVENTS_ERRORS = "FETCH_EVENTS_ERRORS";


export const ADD_USER_TO_EVENT = "ADD_USER_TO_EVENT";

export const FETCH_EVENTS_FROM_GROUP = "FETCH_EVENTS_FROM_GROUP";

export const REJECT_FROM_EVENT = "REJECT_FROM_EVENT";

export const DELETE_EVENT = "DELETE_EVENT";